### ISSUE TITLE
Closing Down

### ISSUE THREAD

**Issue by JaffaKetchup** [fleaflet-docs/flutter_map#14]
Hi there @themisir and @comatory,

_See https://github.com/fleaflet/flutter_map/pull/1286 for more information._

Due to the migration to GitBook (don't worry, the content we wrote is still being used), we no longer need this organisation and the website it provides.  
If you're interested about why we chose GitBook in the end, it was because of the complex system needed to change and auto-deploy the custom Docusaurus website. We decided it would just be easier to use this instead.

Before deleting this repository and organisation, we need to:

- Stop the automatic Netlify deployment - I think you need to do this @themisir
- Delete the existing deployment and (sub)domain - I think you need to do this @themisir
- Remove the Docusaurus website from search results, if possible
- Ensure no valuables are left in here (there shouldn't be, but good to double check)

Hopefully after that, our efforts are done!

Thanks for all your help with this, you've both been credited on the website: <https://docs.fleaflet.dev/credits> :)

**Comment by comatory** [comment]
Great to see the progress on it even though these days I don't do
a lot of mobile development.

I haven't done that much so all the props to you!

**Comment by themisir** [comment]
> Stop the automatic Netlify deployment
> Delete the existing deployment and (sub)domain

Sure.

> Remove the Docusaurus website from search results, if possible

I think it would be good idea to add redirection to the new website once built. I didn't realized that temporary build previews got indexed by search engines, but apparently they did and it's the first search result. So pulling that off will not be straightforward. So instead of showing blank page, I think redirecting them to the new documentation would make sense.

> Ensure no valuables are left in here (there shouldn't be, but good to double check)

I think we can just archive this repository instead of removing it. So everything being done will be preserved.

**Comment by JaffaKetchup** [comment]
Actually, if we delete the domain, I'm assuming Netlify will return 404 or 410, which removes the result from most search engines anyway. Alternatively we can force a 410 Gone result.

I'd prefer to do this instead of redirect, but it's up to you.

**Comment by themisir** [comment]
Actually yeah if we delete it eventually search indexes will be updated. So yeah I'm going to remove it.

**Comment by JaffaKetchup** [comment]
Ok, thanks, I can now see that it's gone.

As I said before, I'm going to transfer this to my personal account, where I can archive it. I will then delete this organisation, just so there is no confusion.

Once more, thanks to both of you :)
