### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by JaffaKetchup** [fleaflet-docs/flutter_map#2]

**Comment by JaffaKetchup** [comment]
>What about structuring sections and subsections first then working on it one by one.

Sure, so get the folder and file layout down? Ok.

Btw, I've renamed the 'getting-started' page to 'go', you should pull.

**Comment by JaffaKetchup** [comment]
https://github.com/fleaflet/flutter_map/issues/991#issue-962149623 looks like a good structure to begin with.
I've got to go now, should be back on tomorrow.

**Comment by TheMisir** [comment]
> Sure, so get the folder and file layout down? Ok, makes more sense as I guess (after we've layed out the structure) there'll be less conflicts.

I think so. Fyi docusaraus uses folder / file names as url paths by default. So I think it might be good if we keep file names and section names as close as possible which have positive impact on SEO / site visibility.

> Should I open a draft PR so it's a bit more public that we're doing this and others can see and maintainers can contribute, or shall I leave it so it's more private until we're ready?

I agree, also we don't have to work on my fork, I just made this up for showcasing what we can do with docusaraus. But we can continue to use it as well, or if you have write permission on main repo, we can create a branch on it and work there. Or idk, I don't have much experience in software collaboration tbh 😅

**Comment by JaffaKetchup** [comment]
> I think so. Fyi docusaraus uses folder / file names as url paths by default. So I think it might be good if we keep file names and section names as close as possible which have positive impact on SEO / site visibility.

Good point.

> I agree, also we don't have to work on my fork, I just made this up for showcasing what we can do with docusaraus. But we can continue to use it as well, or if you have write permission on main repo, we can create a branch on it and work there. Or idk, I don't have much experience in software collaboration tbh 😅

I think we should keep working on this fork, as neither of us have write access to `flutter_map`. In the morning, I'll open a draft PR, so we can keep working here without disturbing `flutter_map`, but simultaneously make it clear we're doing something.

> don't have much experience in software collaboration tbh 😅

Same 😂

Bye 👋

**Comment by JaffaKetchup** [comment]
Morning (for me at least)!
I've laid out the basic tree structure like you suggested, is it good for you?

**Comment by TheMisir** [comment]
> is it good for you?

yep, looks good!

**Comment by JaffaKetchup** [comment]
So I guess just dip in and start writing?

**Comment by TheMisir** [comment]
> So I guess just dip in and start writing?

i think yes, also you don't have to ask me 😅 you've started this documentation before me

**Comment by JaffaKetchup** [comment]
Yeah, good idea.

**Comment by JaffaKetchup** [comment]
I've just pushed another few updates, and one of them changed the icons to a custom icon:
![IconV1](https://user-images.githubusercontent.com/58115698/128540004-5e16d0c7-8cd8-4671-9081-76912b3b5525.png)
...do you like it?

Colours can be changed, or whole icon can be scrapped if you want. If we change the colour, we could also change the colours of the site using the generator at https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima?

**Comment by themisir** [comment]
Hi @JaffaKetchup , can you give me specific sections to work on? I lost track of the works so..

**Comment by JaffaKetchup** [comment]
Haha! Don't worry about it :)

I don't really mind, but if you really want some direction, writing the 3 or more smaller examples under Examples would help a lot.

My plan is to get the web docs done, add it to the README as a beta docs, then work on the internal source docs if that's good with you.
